# Server Configuration
server:
  port: 8093
  undertow:
    worker-threads: 200
  servlet:
    session:
      persistent: false
      store-dir: /var/log/app

# Oracle settings and Pool Connection
spring:
  profiles:
    active: oauth-security #basic-security
  application:
    name: algamoney-api
  datasource:
    #url: jdbc:oracle:thin:@10.20.1.113:1521:omni19c
    url: jdbc:mysql://localhost:3306/algamoney?useTimezone=true&serverTimezone=UTC
    #username: WSALGAMONEY
    username: root
    #password: omnidev
    password:
    #driver-class-name: oracle.jdbc.OracleDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2 # numero maximo de conexoes inativas mantidas pelo KikariCP em um conjunto de conexoes (senao tiver ningem usando o sistema esse é o numero máximo de conexoes que ficarão em memoria aguardando para ser usado)
      maximum-pool-size: 10 # maximo de conexóes que é aberta
      pool-name: AlgamoneyApiPool
      idle-timeout: 9000 # tempo ocioso para conexão, ou seja, tempo que uma conexão vai ficar ociosa após ser usada para após esse tempo essa conexao morrer
      isolate-internal-queries: true
      connection-test-query: SELECT 1 from DUAL
      connection-timeout: 18000 # tempo maximo em milisegundos que um cliente irá aguardar por uma conexao (se em 18 segundos não tiver uma conexao disponivel ocorre erro de timeout)
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.Oracle10gDialect
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
        id: #MYSQL - não gerar sequence
          new_generator_mappings: false
        jdbc:
          batch_size: 5
  batch: #cria as tabelas default do spring batch
    initialize-schema: ALWAYS
  liquibase:
    contexts: local
    change-log: classpath:db/changelog/master.xml
  redis.cluster.enable: false
  redis:
    host: 192.168.0.60 #localhost
    port: 6379
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  rabbitmq:
    addresses: 192.168.0.60 #localhost
    port: 5672
    username: adrianond
    password: secret
    virtual-host: adrianond
app:
  swagger.host: localhost:8080
  algamoney:
    rabbit:
      config:
        initialInterval: 60000 # 1min
        maxInterval: 120000 # 2min
        multiplier: 1 # linear, uma tentativa cada 'initialInterval'
        retries: 1
        consumers: 1
        maxConsumers: 10
        default-message-converter: true
      bindings:
        -
          topic: algamoney.event.save.phone
          routing-key: algamoney.event.save.phone
          queue: algamoney.event.save.phone.queue
          dlx: algamoney.event.save.phone.dlx
          dlq: algamoney.event.save.phone.dlq
          declare: true
        -
          topic: algamoney.event.carga.pessoa
          routing-key: algamoney.event.carga.pessoa
          queue: algamoney.event.carga.pessoa.queue
          dlx: algamoney.event.carga.pessoa.dlx
          dlq: algamoney.event.carga.pessoa.dlq
          declare: true
    seguranca:
      enableHttps: false
    person:
      url: https://gsdktzz0lb.execute-api.us-east-1.amazonaws.com/dev
    mail:
      host: smtp.mail.yahoo.com
      port: 587
      username: email@yahoo.com.br
      password: senha
    scheduler:
      efetuar-carga-pessoa:
        enabled: false
        cron: !!str "0 0 9 * * *"  # todos os dias as 9:00:00 (segundo 0, minuto 0, 9 horas, dia do mes, mes, dia da semanma)
      envio-email:
        enabled: false
    job:
      tamanhoLote: 5
    s3:
      accessKeyId: AKIA2XRSHTYWFB2HP776
      secretAccessKey: 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
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

  web: DEBUG


